language: rust

os: linux
dist: focal

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

jobs:
  include:
    - os: linux
      dist: focal
      rust: nightly

script:
  - rustup component add llvm-tools-preview
  - export RUSTFLAGS="-Zinstrument-coverage"
  - cargo build --verbose $CARGO_OPTIONS
  - cargo test --verbose $CARGO_OPTIONS
  - |
    ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --token $CODECOV_TOKEN -o ./lcov.info;
    bash <(curl -s https://codecov.io/bash) -f lcov.info;
